// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea3_GestionEmpleados_C06225.Data;

#nullable disable

namespace Tarea3_GestionEmpleados_C06225.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501160117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Tarea3_GestionEmpleados_C06225.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellidos = "Pérez",
                            Departamento = "TI",
                            FechaIngreso = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            Salario = 850000m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellidos = "Rodríguez",
                            Departamento = "RRHH",
                            FechaIngreso = new DateTime(2021, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María",
                            Salario = 600000m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apellidos = "Sánchez",
                            Departamento = "TI",
                            FechaIngreso = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos",
                            Salario = 950000m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apellidos = "López",
                            Departamento = "Contabilidad",
                            FechaIngreso = new DateTime(2020, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana",
                            Salario = 550000m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Apellidos = "García",
                            Departamento = "TI",
                            FechaIngreso = new DateTime(2022, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Luis",
                            Salario = 1200000m
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Apellidos = "Martínez",
                            Departamento = "Ventas",
                            FechaIngreso = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Elena",
                            Salario = 450000m
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Apellidos = "Gómez",
                            Departamento = "Marketing",
                            FechaIngreso = new DateTime(2021, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pedro",
                            Salario = 700000m
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Apellidos = "Vargas",
                            Departamento = "RRHH",
                            FechaIngreso = new DateTime(2022, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sofía",
                            Salario = 620000m
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Apellidos = "Castro",
                            Departamento = "TI",
                            FechaIngreso = new DateTime(2020, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Diego",
                            Salario = 1500000m
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Apellidos = "Mora",
                            Departamento = "Ventas",
                            FechaIngreso = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Lucía",
                            Salario = 480000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
